### ISSUE TITLE
Wrong dependency constraint

### ISSUE THREAD

**Issue by einarj** [tenex/rails-assets#317] opened 2016-04-01 10:02 UTC
The bower.json for angular-ui-grid specifies the following dependency:
`"dependencies": {
    "angular": ">=1.2.16 1.4.x"
  },`

This gets translated into the following Bundler dependency constraint: `rails-assets-angular (>= 1.2.16, ~> 1.4.0)`

I believe that it is not possible to satisfy this contstraint without having version 1.4.x of rails-assets-angular. When I try to install 3.1.1 of rails-assets-angular-ui-grid, I get the following error:

```
Bundler could not find compatible versions for gem "rails-assets-angular":
  In Gemfile:
    rails-assets-angular-ui-grid (= 3.1.1) ruby depends on
      rails-assets-angular (>= 1.2.16, ~> 1.4.0) ruby

    rails-assets-angular (1.2.17)
```

**Comment by hut8** [comment] 2016-04-06 01:34
Thanks for the issue. I learned something new from this :smile: 

https://github.com/bower/spec/blob/master/json.md#dependencies defines that field as:

> Value must be a valid semver range, a Git URL, or a URL (inc. tarball and zipball).

The [semver range](https://github.com/npm/node-semver#ranges) link points out:

> Comparators can be joined by whitespace to form a comparator set, which is satisfied by the intersection of all of the comparators it includes.

[intersection](https://en.wikipedia.org/wiki/Intersection_%28set_theory%29) means

> the intersection A ∩ B of two sets A and B is the set that contains all elements of A that also belong to B (or equivalently, all elements of B that also belong to A), but no other elements

That dependency spec looks pretty messed up to me when looked at with these definitions in front of me. The intersection of the set `>=1.2.16 ∩ 1.4.x` seems to equal `1.4.x` but I failed a lot of math in college :stuck_out_tongue: The conjunction seems to be consistent with how Bundler handles it, also.

When you say:

> I believe that it is not possible to satisfy this contstraint without having version 1.4.x of rails-assets-angular. 

I concur. That is the correct behavior, yes?

Can you run `bundle update rails-assets-angular rails-assets-angular-ui-grid`? I'm working on a project that uses both right now, actually. My gemfile has (among other things):

```
    rails-assets-angular-ui-grid (3.1.1)
      rails-assets-angular (~> 1.4.0, >= 1.2.16)
```

I'm marking this as pending feedback. Please let me know exactly what the expected behavior vs. the actual behavior is, or whether or not I've clarified. Thanks again!

**Comment by einarj** [comment] 2016-04-06 09:20
After reading through the Bower documentation on dependencies and playing around with the semver tool, I believe that the angular-ui-grid library itself has a dependancy range that can only be satisified with angular 1.4.x.

I'll file an issue there.

But just to add some experiments:
My angular contraint is set to `gem 'rails-assets-angular', '= 1.2.16'
`
If I run `bundle update rails-assets-angular rails-assets-angular-ui-grid`

It will only install version 3.0.1 of rails-assets-angular-ui-grid.

If I remove the version dependency from rails-assets angular and then run the bundle update command it doesn’t actually update anything. I still end up with 1.2.16 for angular and 3.0.1 for ui-grid.

If I specifiy version 3.1.1. of ui-grid and set no version dependency for angular it fails with the previous error:

```
Bundler could not find compatible versions for gem "rails-assets-angular":
  In Gemfile:
    rails-assets-angular-ui-grid (= 3.1.1) ruby depends on
      rails-assets-angular (>= 1.2.16, ~> 1.4.0) ruby

    rails-assets-angular-resource (>= 0) ruby depends on
      rails-assets-angular (1.2.16)
```

**Comment by hut8** [comment] 2016-04-27 16:14
I'm going to go ahead and close this because it looks like it's working as designed, and the dependencies for angular-ui-grid may have been a bit off. Let me know if that's not the case :+1:

**Closed as completed by hut8** 2016-04-27 16:14 UTC
