### ISSUE TITLE
Cannot add component that is made up of only dependencies

### ISSUE THREAD

**Issue by joshjordan** [tenex/rails-assets#347] opened 2016-05-22 19:48 UTC
Cloning issue:

https://github.com/rails-assets/rails-assets/issues/264#issuecomment-174006868 [Issue automatically imported by https://github.com/controlgroup/CSV-GitHub-import-export]

**Comment by hut8** [comment] 2016-05-26 20:17
This is actually a duplicate of #132

**Closed as completed by hut8** 2016-05-26 20:17 UTC
