### ISSUE TITLE
building has stopped since 20170209

### ISSUE THREAD

**Issue by debbbbie** [tenex/rails-assets#393] opened 2017-02-16 03:09 UTC
I got status from: https://rails-assets.org/status 

@ctrochalakis @railsbros-dirk @Peeja @bmaland @geoffgarside

**Comment by hut8** [comment] 2017-02-16 03:28
Checking now

**Comment by hut8** [comment] 2017-02-16 03:37
Should be fixed now. We had some major hardware issues recently which seems to have disrupted Sidekiq somehow, although I haven't found the precise etiology yet.

**Comment by hut8** [comment] 2017-02-16 04:04
I'm going to go ahead and close this because Sidekiq is chewing through the queue pretty quickly. I'll post a separate issue once I diagnose the cause.

**Closed as completed by hut8** 2017-02-16 04:04 UTC
