### ISSUE TITLE
Service down

### ISSUE THREAD

**Issue by jrasanen** [tenex/rails-assets#65] opened 2016-03-24 10:34 UTC
We are receiving a lot of errors:

> This website is under heavy load (queue full)
> 
> We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.

and "https://rails-assets.tenex.tech/" keeps redirecting to "https://rails-assets.org/"

**Comment by jrgifford** [comment] 2016-03-24 13:40
Still an issue!

**Comment by joshjordan** [comment] 2016-03-24 14:21
Working on it. We have a large backlog of gems to build since switching over to the new server.

You should update your sources to point at https://rails-assets.org, but that isn't going to solve the problem in the short term. We will have some intermittent downtime today while the app chews through the backlog on the new machine. Trying to minimize that; I'll poke you when the queue is empty so you can bundle.

Sorry for the inconvenience! We're working hard on it.

**Comment by joshjordan** [comment] 2016-03-24 14:26
I'm taking the server offline to free up some resources right now, in hopes that we can get through a big chunk of the backlog. We weren't able to serve bundle requests anyway.

**Comment by jrgifford** [comment] 2016-03-24 15:03
OK, thanks for keeping us updated!

**Comment by hut8** [comment] 2016-03-24 16:18
I am actively working on getting the worker moved to a new instance. Will continue to update.

**Comment by hut8** [comment] 2016-03-24 16:45
I have moved the worker off of the main server, and am working on hooking up the new instance I'm provisioning to actually build the gems and put them into the gem storage. The site is back up, although don't count on new gems being built quickly.

**Comment by hut8** [comment] 2016-03-24 17:06
I had to bounce the main production webserver real quick in order to enable private networking; it's back up now.

**Comment by hut8** [comment] 2016-03-24 17:29
Over the last 30 minutes (since I bounced the server) we've gotten about 282 requests per minute processed by Passenger. I have shrunk the number of Passenger processes to 4 in order to reduce memory usage, and surprisingly there are still  0 requests in queue. So that was an easy win for reducing memory usage.

I'm working hard on splitting out a separate worker instance, but that will take a little bit of time. In the mean time, the load hasn't hit 4, and memory usage seems semi-stable, and I have brought back up the worker on the webserver itself (how it was originally). I will keep a close eye on it.

**Comment by LPiner** [comment] 2016-03-24 18:20
I'm not sure if this is you guys or not but my bundle install has been failing all day today. 

Fetching gem metadata from https://rails-assets.org/....
Fetching version metadata from https://rails-assets.org/..
Could not find rails-assets-backbone.babysitter-0.1.11 in any of the sources

**Comment by hut8** [comment] 2016-03-24 18:25
That's our server, yes. I added that version into the queue of things to build. Not 100% of the gems that were on the old service were transferred to the new one (my apologies for this, but it's extremely hard to synchronize them with no gap in between). These are the ones that were there:

```
["0.0.5", "0.1.9", "0.1.8", "0.0.4", "0.1.7", "0.0.3", "0.1.3", "0.0.2", "0.1.10", "0.1.6", "0.1.4", "0.1.5", "0.1.1-1", "0.1.1", "0.1.2", "0.1.0", "0.0.6", "0.0.1"]
```

It will be available shortly.

**Comment by LPiner** [comment] 2016-03-24 18:27
Thanks for all your hard work mate, it doesn't go unnoticed!

**Comment by hut8** [comment] 2016-03-24 21:15
We decided to roll back for now until I can get the infrastructure a bit more stable. We had a very old snapshot (early February) of Monterail's production database, so we're updating that and scaling the servers better. We'll have our mirror up and running again shortly :+1: Sorry for the inconvenience and thanks, everyone, for your patience!

**Comment by hut8** [comment] 2016-03-27 15:02
Infrastructure update: 

* For the last 18 hours, rails-assets.org has been pointed at the new servers. During that time we've had less than 5 seconds of downtime which was caused by me renewing SSL certs via Letsencrypt. Now that I have them, that won't have to happen again. The load average hasn't even hit 1 during that time, although that's in part due to it being the weekend (specifically Easter weekend).

* There seems to be some sort of memory issue with the Passenger worker process (i.e., in the application code). After some event (it's hard to pinpoint exactly what without more work), the RSS usage grows to 1.4 GB but does not grow after that. This has happened on several processes. @joshjordan and I are looking into this. Help is definitely appreciated, and I'm opening a separate issue. But since the application code hasn't changed significantly from what was on the old server, this isn't something to hold us up and there are easy workarounds for this until we find the precise cause.

* The workers are on a separate machine and are doing just fine.

* We abandoned S3 because the S3FS implementation that we were using as a stop-gap (https://github.com/s3fs-fuse/s3fs-fuse) caused a large number of problems. We're using good ol' NFS now and it seems to be working really well.

* We've set up StatusCake and Librato to monitor things closely, and I bought an extra monitor that's trained on rails-assets.org in a tmux session full of colorful metrics (at least, that was my excuse to get another monitor ;).

As a result, I'm going to go ahead and close this issue. Please file new one if things break, though I am pretty confident in the stability now (although, it is Easter so the load is pretty light).

**Closed by hut8** 2016-03-27 15:02 UTC
Labels: infrastructure, urgent

**Comment by joshjordan** [comment] 2016-03-27 16:19
:+1:
