### ISSUE TITLE
Invalid SSL cert on website

### ISSUE THREAD

**Issue by resgraph** [tenex/rails-assets#391] opened 2017-02-08 05:27 UTC
The SSL cert for the domain rails-assets.org expired at 8pm Feb. 7, 2017. Cannot deploy due to SSL errors. Please renew cert.

**Comment by hut8** [comment] 2017-02-08 05:29
Closing as duplicate of #390 which was resolved moments ago.

**Closed as completed by hut8** 2017-02-08 05:29 UTC
