### ISSUE TITLE
Unable to POST new version to /components (500 error)

### ISSUE THREAD

**Issue by vlymar** [tenex/rails-assets#427] opened 2018-06-19 19:28 UTC
```
curl -H "Content-Type: application/json" \
     -X POST \
     -d "{ \"component\": { \"name\": \"formrenderer-base\", \"version\": \"1.3.8\" } }" \
     "https://rails-assets.org/components"
```

Returns:

```html
<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
  }

  div.dialog {
    width: 25em;
    margin: 4em auto 0 auto;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 4em 0 4em;
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  body > p {
    width: 33em;
    margin: 0 auto 1em;
    padding: 1em 0;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow:0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  <!-- This file lives in public/500.html -->
  <div class="dialog">
    <h1>We're sorry, but something went wrong.</h1>
  </div>
  <p>If you are the application owner check the logs for more information.</p>
</body>
</html>
```

**Comment by vlymar** [comment] 2018-06-21 19:07
I see our library with the "undefined method 'path'" error on the build status page, seems related to this previous issue: https://github.com/tenex/rails-assets/search?q=undefined+method+%60path%27&type=Issues

**Comment by hut8** [comment] 2022-07-29 20:10
Duplicate of #418

**Closed as completed by hut8** 2022-07-29 20:10 UTC
