### ISSUE TITLE
Slow and backlogged?

### ISSUE THREAD

**Issue by sfcgeorge** [tenex/rails-assets#396] opened 2017-03-30 10:18 UTC
I noticed `bundle update` was taking many seconds to do the `Fetching gem metadata from https://rails-assets.org/...` etc steps.

Checking the site I see a lot of pending builds and pending reindex for various versions of `mozilla--pdfjs-dist#X.X.XXX`, I think pdfjs is rather huge so maybe that's clogging up the system?

Dunno how much monitoring you have, maybe there's no problem.

**Comment by sfcgeorge** [comment] 2017-03-30 10:58
Fast again now and the backlog is gone.

Up to you whether you want to close. It might be worth doing something about not building hundreds of ancient versions of things though as it'll only grow.

**Comment by hut8** [comment] 2017-03-30 21:25
Hey there. Thanks for the report!

We do have quite a bit of monitoring in place. The CPU was high at this time, which was caused by building a lot of versions of that gem. But the real issue here is that rendering the old index format simply takes a lot of CPU as well. This would resolve it: https://github.com/tenex/rails-assets/issues/332

Because that's the "real" resolution, I'm going to go ahead and close this. Thanks again!

**Closed as completed by hut8** 2017-03-30 21:25 UTC
