### ISSUE TITLE
rails-assets-bootstrap-sass missing woff2 fonts

### ISSUE THREAD

**Issue by prosanelli** [tenex/rails-assets#222] opened 2015-02-11 16:26 UTC
the bootstrap-sass gem has woff2 fonts: 
https://github.com/twbs/bootstrap-sass/tree/v3.3.3/assets/fonts/bootstrap

there are not present in the rails-assets-bootstrap-sass gem
![screen shot 2015-02-11 at 11 23 50 am](https://cloud.githubusercontent.com/assets/2065666/6150997/d78a6ef2-b1e0-11e4-8153-92cc3f66c0ba.png)

**Comment by sheerun** [comment] 2015-02-11 16:39
Duplicate of #218

**Closed as completed by sheerun** 2015-02-11 16:39 UTC
