### ISSUE TITLE
jquery-ui gem doesn't contain all expected stylesheet files

### ISSUE THREAD

**Issue by jezstephens** [tenex/rails-assets#219] opened 2015-02-04 13:23 UTC
Looking at `rails-assets-jquery-ui`, the gem includes only the following stylesheet files:

```
jquery-ui/jquery-ui.scss
jquery-ui/theme.scss
```

If you look in the [source repo](https://github.com/components/jqueryui), there's loads more CSS for all the different jQuery UI themes ([example](https://github.com/components/jqueryui/tree/master/themes/base)).

It looks like this should all be included in the built gem. Any idea what's wrong?

**Comment by sheerun** [comment] 2015-02-12 04:57
Because `bower.json` doesn't list any main `.css` files, we simply guess what files to include..

It's duplicate of #191

**Closed as completed by sheerun** 2015-02-12 04:57 UTC
